[theme]
primaryColor = "#7030A0"
backgroundColor = "#F3F3F3"
secondaryBackgroundColor = "#F3F3F3"
textColor = "#1A1A1A"
font = "sans serif"
base = "light"

[server]
enableCORS = false
enableXsrfProtection = false
